language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r test_requirements.txt
script:
  - ./linters.sh && coverage run --source=flask_exceptions/ setup.py test
after_success:
  - coveralls
